# Kafka JMX 监控配置
# 用于 Prometheus JMX Exporter

rules:
  # Kafka Broker 指标
  - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
    name: kafka_server_$1_$2
    labels:
      clientId: "$3"
      topic: "$4"
      partition: "$5"
    type: GAUGE

  - pattern: kafka.server<type=(.+), name=(.+), topic=(.+), partition=(.*)><>Value
    name: kafka_server_$1_$2
    labels:
      topic: "$3"
      partition: "$4"
    type: GAUGE

  - pattern: kafka.server<type=(.+), name=(.+)><>Value
    name: kafka_server_$1_$2
    type: GAUGE

  # Kafka Producer 指标
  - pattern: kafka.producer<type=(.+), name=(.+), clientId=(.+)><>Value
    name: kafka_producer_$1_$2
    labels:
      clientId: "$3"
    type: GAUGE

  # Kafka Consumer 指标
  - pattern: kafka.consumer<type=(.+), name=(.+), clientId=(.+)><>Value
    name: kafka_consumer_$1_$2
    labels:
      clientId: "$3"
    type: GAUGE

  # JVM 指标
  - pattern: java.lang<type=(.+), name=(.+)><>Value
    name: jvm_$1_$2
    type: GAUGE

  - pattern: java.lang<type=(.+), name=(.+)><>Count
    name: jvm_$1_$2_count
    type: COUNTER
